version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn app.server:app --host ${HOST} --port ${WEB_PORT} --reload"
    volumes:
      - ./backend:/app:cached
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_HOST_IP=${HOST}
      - REACT_APP_BACKEND_PORT=${WEB_PORT}
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    ports:
      - 3000:3000
    depends_on:
      - backend
