version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn backend.server:app --host ${HOST} --port ${WEB_PORT} --reload"
    volumes:
      - .:/backend
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
