"""Change some fileds of Stock model to Nullable

Revision ID: 783330ddd084
Revises: b75961d4b222
Create Date: 2021-09-18 17:13:21.492490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '783330ddd084'
down_revision = 'b75961d4b222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'pe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'forward_pe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'peg',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'ps',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'pb',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'div',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'roa',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'roe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'roi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'curr_r',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'quick_r',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'debt_eq',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'gross_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'oper_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'profit_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'volume',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'volume',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stocks', 'profit_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'oper_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'gross_m',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'debt_eq',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'quick_r',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'curr_r',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'roi',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'roe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'roa',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'div',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'pb',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'ps',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'peg',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'forward_pe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'pe',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stocks', 'market_cap',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocks', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocks', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocks', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocks', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
