"""First migration

Revision ID: b75961d4b222
Revises: 
Create Date: 2021-09-18 16:35:17.251739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75961d4b222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('market_cap', sa.String(), nullable=False),
    sa.Column('pe', sa.Float(), nullable=False),
    sa.Column('forward_pe', sa.Float(), nullable=False),
    sa.Column('peg', sa.Float(), nullable=False),
    sa.Column('ps', sa.Float(), nullable=False),
    sa.Column('pb', sa.Float(), nullable=False),
    sa.Column('div', sa.Float(), nullable=False),
    sa.Column('roa', sa.Float(), nullable=False),
    sa.Column('roe', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('curr_r', sa.Float(), nullable=False),
    sa.Column('quick_r', sa.Float(), nullable=False),
    sa.Column('debt_eq', sa.Float(), nullable=False),
    sa.Column('gross_m', sa.Float(), nullable=False),
    sa.Column('oper_m', sa.Float(), nullable=False),
    sa.Column('profit_m', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
